name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet test WsaManager.Native.sln -p:Platform=x64
      - run: dotnet build WsaManager.Native.sln -p:Platform=x64
